<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="CARRITO.aspx.cs" Inherits="TPWEB_EQUIPO3.CARRITO" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">



        <style>

    .Fondo{

        background-color:brown;

        color: aliceblue;
        padding: 50px;
        text-align: center;

    }

</style>
   

<div class="Fondo">   

       
     <h2>         CARRITO </h2>

    


</div>


    <body>

        <div>
    
            <asp:GridView ID="dgbCarrito" runat="server"  CssClass="table" AutoGenerateDeleteButton="True"></asp:GridView>


        </div>

    </body>
   






</asp:Content>
